// Pure formatter: trip plan -> plain text for clipboard / Notes app / text message.
// No DOM, no network. Input shape matches what planLoad already produces in index.html.

function formatTripText(trip) {
  const {
    pickupAddr, deliveryAddr,
    plan, gap, finalLegMiles, detourMax, appVersion, fuelBookRev
  } = trip;

  const lines = [];
  lines.push('FUELPOST TRIP PLAN');
  lines.push('');
  lines.push(`Pickup:   ${pickupAddr}`);
  lines.push(`Delivery: ${deliveryAddr}`);
  lines.push('');

  if (plan && plan.length) {
    lines.push('FUEL STOPS');
    plan.forEach((s, i) => {
      const leg = s.legMiles != null ? `  (${s.legMiles} mi leg)` : '';
      const tier = s.tier === 'excl' ? '  [Exclusive]' : '';
      lines.push(`${i + 1}. ${s.name} \u2014 mile ${Math.round(s.mile)}${leg}${tier}`);
    });
  } else if (!gap) {
    lines.push('No fuel stop needed \u2014 destination is within range.');
  }

  if (detourMax && detourMax > 8) {
    lines.push('');
    lines.push(`Note: no network stop within 8 mi of the route, this plan uses stops up to ${detourMax} mi off.`);
  }

  if (finalLegMiles != null && plan && plan.length) {
    lines.push('');
    lines.push(`Final leg to delivery: ${finalLegMiles} mi`);
  }

  if (gap) {
    lines.push('');
    lines.push(`WARNING \u2014 network fuel gap: no Covenant stop between mile ${gap.fromMile} and mile ${gap.deadMile}.`);
    lines.push('Out-of-network fuel needs approval \u2014 call Driver Support 423-463-3680.');
  }

  lines.push('');
  lines.push(`Generated by FuelPost${appVersion ? ' v' + appVersion : ''}${fuelBookRev ? ' \u00b7 ' + fuelBookRev : ''}`);

  return lines.join('\n');
}

module.exports = { formatTripText };
